# Generated by Django 3.2.3 on 2021-05-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20210529_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['-date']},
        ),
    ]
