# Generated by Django 3.2.3 on 2021-05-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_date_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['start_time']},
        ),
    ]
