# Generated by Django 3.2.3 on 2021-05-30 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime.today),
        ),
    ]
