# Generated by Django 3.2.3 on 2021-06-03 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20210531_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(blank=True, choices=[('Today', datetime.datetime(2021, 6, 3, 23, 8, 56, 229374)), ('Tomorrow', datetime.datetime(2021, 6, 4, 23, 8, 56, 229385))]),
        ),
    ]
