# Generated by Django 3.2.3 on 2021-06-03 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_date_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(blank=True, choices=[(datetime.datetime(2021, 6, 3, 23, 13, 24, 143733), 'Today'), (datetime.datetime(2021, 6, 4, 23, 13, 24, 143744), 'Tomorrow')]),
        ),
    ]
