# Generated by Django 3.2.4 on 2021-06-21 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_alter_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='date',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
