# Generated by Django 3.2.4 on 2021-06-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_auto_20210621_1904'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='date',
            name='id_index',
        ),
    ]
