# Generated by Django 3.2.4 on 2021-07-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='city',
            name='icon',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='city',
            name='temperature',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
