# Generated by Django 3.2.5 on 2021-08-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210710_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todos', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('notes', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
        ),
    ]
