# Generated by Django 3.2.5 on 2021-08-10 16:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_app_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.AddField(
            model_name='app',
            name='display_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, max_length=50, null=True, size=None),
        ),
    ]
