# Generated by Django 3.2.6 on 2021-08-13 06:46

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210813_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, size=[128, 128], upload_to='media/profile_pics'),
        ),
    ]
