# Generated by Django 3.2.6 on 2021-08-13 07:48

from django.db.models.fields.files import FileField
from config.storage_backends import ProfileMediaStorage
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_setting_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, size=[128, 128], storage=ProfileMediaStorage, upload_to=''),
        ),
        migrations.AddField(
            model_name='setting',
            name='profile_pic',
            field=FileField(storage=ProfileMediaStorage),
        )
    ]
