# Generated by Django 3.2.6 on 2021-08-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_city_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='app_display_dict',
            field=models.JSONField(blank=True, default='{"todos": "True", "notes": "True"}', null=True),
        ),
    ]
