# Generated by Django 3.2.6 on 2021-08-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_setting_app_display_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='app_display_dict',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
