# Generated by Django 3.2.6 on 2021-08-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_setting_app_display_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='books',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
