# Generated by Django 3.2.6 on 2021-08-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_setting_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='books',
        ),
    ]
