# Generated by Django 3.2.4 on 2021-06-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_chapter_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
