# Generated by Django 3.2.4 on 2021-06-24 18:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210625_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='nothing'),
            preserve_default=False,
        ),
    ]
