# Generated by Django 3.2.4 on 2021-06-10 10:32

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20210610_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
