# Generated by Django 3.2.6 on 2021-09-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_auto_20210816_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
