# Generated by Django 3.2.6 on 2021-09-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_note_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-order']},
        ),
        migrations.AlterField(
            model_name='note',
            name='order',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
