# Generated by Django 3.2.6 on 2021-09-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_alter_note_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='order',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
